Siri Hemsley & Anna Lenksjö - Project Auth
Technigo/project-auth pull request #104
Opened 2021-05-27 14:14 UTC by sirimatsdotter

**Link to my deployed project:**
Frontend: https://youthful-liskov-e3177b.netlify.app/
Backend: https://siri-anna-auth-backend.herokuapp.com

**My reflections on how this week's project turned out:**

- Overall it went well and it was fun to do our first real fullstack application!
- It was great to refresh our knowledge on so many different things, such as React Router, Redux Store.
- Really good to learn about authorization and how to create logins etc

**Things I'd like to have clarified or explained in more detail:**

- As mentioned in the README we do still have one error which we don't know exactly what it means. Would be great to get some more explanation on this :)

_"index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
in LogIn (at App.js:43)"_

2021-06-02 16:38 UTC, idasylven approved these changes
Great job on this assignment! Clean and well-structured code, and we get the impression you really fully understand what you're doing 💥 🍾 

Nice README explaining your process and what you would like to improve in the future, with more specific error messages and the logged in site to be a bit more complex 👍🏻 😻

We have very few improving comments except for being able to sign up without a password, and also being able to access the secret content without a password. Perhaps you want to look into that 👀. (And let us in on the solution 😝 )

APPROVED! ✨

2021-06-02 16:38 UTC, idasylven commented on backend/server.js
> +})
Cool that you used axios! 😎

2021-06-02 16:38 UTC, idasylven commented on frontend/src/App.js
> +import styled from 'styled-components'
Great job using styled components! 👍🏻  Perhaps you could consider using macro too, if you wish for the class names to be displayed in dev tools ⚒️

2021-06-02 16:38 UTC, idasylven commented on frontend/src/components/StyledBtn.js
> +`
In the Sign Up or Log In form, perhaps you could consider adding some margin to the bottom of the button or padding to the bottom of the form. When an error message is displayed, it's getting a little cramped ➡️ ⬅️

2021-06-05 07:47 UTC, KarolCislowski requested changes
It looks really nice but you need to do some fixes:
1. for sure you need to kill the Netlify error interruption issue, instruction is in the comment with screenshot. 
2. Analise differences between my and your useEffect approach and apply it to your code now and for future projects 😜 


Because your graduation is so soon please let me know on slack (a short note with a link to this PR) if either you finish it or still have the error you mentioned, then I will investigate it with you after Netlify will not interrupt us 🕵🏻

2021-06-05 07:47 UTC, KarolCislowski commented on backend/server.js
> +     })
👍🏻

2021-06-05 07:47 UTC, KarolCislowski commented on frontend/src/App.js
> +color: #6A7885;
indentation

2021-06-05 07:47 UTC, KarolCislowski commented on frontend/src/components/Content.js
> +    <StyledButton onClick={onLogOut}>Log out</StyledButton>
indentation

2021-06-05 07:47 UTC, KarolCislowski commented on frontend/src/components/Content.js
> +  },[accessToken, dispatch])
`useEffect` hook should be always at the root of your component. Never nest it in a different method even the other `useEffect`. 

```jsx

useEffect(() => {
  if (!accessToken) {
    history.push('/')
  } else {
    const options = {
      method: 'GET',
      headers: {
        Authorization: accessToken
      }
    }
    fetch(API_URL('session'), options)
      .then(res => res.json())
      .then(data => {
        if (data.success) {
          setImgsrc(data.images[0].url)
        } else {
          dispatch(user.actions.setErrors(data))
        }
      })
  }
}, [accessToken, dispatch])


```

2021-06-05 07:47 UTC, KarolCislowski commented on frontend/src/reducers/user.js
> +})
great reducer 👍🏻

2021-06-05 07:47 UTC, KarolCislowski commented on frontend/src/components/SignUp.js
> +          history.push('/login')
Why? Your API already provided you with all credentials here so why not log your user behind the scenes and redirect straight to the content?

2021-06-05 07:50 UTC, KarolCislowski requested changes

2021-06-05 07:50 UTC, KarolCislowski commented on pull_request_template.md
> +in LogIn (at App.js:43)"
To fix it you need to create `_redirects` file in the `public` directory of your react project and paste it inside:
``` 
/* /index.html 200
```

![image](https://user-images.githubusercontent.com/50926159/120884425-740a1d00-c5e3-11eb-8bc9-5093b2558132.png)

2021-06-08 12:13 UTC, KarolCislowski approved these changes
Great Project 🥇

2022-04-21 14:54 UTC, closed without merging