Project auth - Andrea L & Pauline A
Technigo/project-auth pull request #105
Opened 2021-05-28 10:42 UTC by Andrealarsson

Link to my deployed project:
Frontend:
https://practical-wozniak-d60eff.netlify.app/Login 
Backend: 
https://project-auth-paan.herokuapp.com

2021-05-28 12:27 UTC, julialeonieros reviewed
Nice and clean project! Easy to read code. We like that you have divided up the components and pages in separate files ✌️ Maybe add that this was a pair-programming project in the Read-Me? Just a tip 😊  You can also delete the file 'SubmitButton.js' that's not in use. Good job! 🥳

2021-05-28 12:27 UTC, julialeonieros commented on README.md
> +https://practical-wozniak-d60eff.netlify.app/Login
A tip! Remove "login" from the URL, otherwise you'll get an error (404) when opening the link

2021-05-28 12:27 UTC, julialeonieros commented on backend/server.js
> +    minlength: 5
NIce that you've implemented validation on the username! 👍

2021-05-28 12:27 UTC, julialeonieros commented on backend/server.js
>  // Add middlewares to enable cors and json body parsing
Maybe remove these comments?

2021-05-28 12:27 UTC, julialeonieros commented on frontend/src/components/TextInput.js
> +import styled from 'styled-components'
Another tip! Use 'styled-components/macro' to make is easier to read in dev tools

2021-05-28 12:27 UTC, julialeonieros commented on frontend/src/pages/Login.js
> +            <TextInput value={value.password} type="password" handleChange={handleChange('password')} title="Password" />
Maybe some linebreaks here to make it more readable 😇

2021-06-05 08:18 UTC, KarolCislowski requested changes
It is really nice app but you need to clean it up and persist your user in the local storage to avoid refreshing.

Because your graduation is so soon please let me know on slack (a short note with a link to this PR) when you finish fixing your app.

2021-06-05 08:18 UTC, KarolCislowski commented on frontend/src/pages/Login.js
> +align-items: center;`
indentations

2021-06-05 08:18 UTC, KarolCislowski commented on backend/server.js
> +  }
nicely constructed model 👍🏻

2021-06-05 08:18 UTC, KarolCislowski commented on frontend/src/pages/Login.js
> +            console.log(data)
Remove your console logs. It is really important!

2021-06-05 08:18 UTC, KarolCislowski commented on frontend/src/pages/Login.js
> +            .catch(error => console.log("error"));
👎🏻

2021-06-05 08:18 UTC, KarolCislowski commented on frontend/src/pages/Main.js
> +    const dispatch = useDispatch();
Really bad indentation. 0 and 4 spaces- should be 2 in both cases.

2021-06-05 08:18 UTC, KarolCislowski commented on frontend/src/reducers/user.js
> +export default user;
You need to store your user in the `localStorage` to prevent logging out after refreshing.

2021-06-19 10:38 UTC, KarolCislowski approved these changes
Great App 🥇

2022-04-21 14:54 UTC, closed without merging