Project-auth by Åsa Hildebrand, Linnéa Helén & Katharina Liebig
Technigo/project-auth pull request #108
Opened 2021-05-28 11:52 UTC by katliebig

Link to my deployed project:
FE: https://secrets-project-auth.netlify.app/
BE: https://secrets-project-auth.herokuapp.com/

My reflections on how this week's project turned out: we're happy! :)

Things I'd like to have clarified or explained in more detail: -

2021-06-03 10:00 UTC, newmarkdev approved these changes
Well done ! we don't have that much to add but guess for a final product you could add styling and some API docs 😀

2021-06-05 08:57 UTC, KarolCislowski requested changes
It is really nice app but you need to style it and persist your user in the local storage to avoid refreshing.


Because your graduation is so soon please let me know on slack (a short note with a link to this PR) when you finish fixing your app.

2021-06-05 08:57 UTC, KarolCislowski commented on README.md
> +FE: https://secrets-project-auth.netlify.app/login
Too retro. Remember that you will show your project to the recruiters... and guess how high are your chances that he/she will click anything when will see something unstyled whatsoever? You are 3 person team, and there is no way that you can't find time to put some love into it.

2021-06-05 08:57 UTC, KarolCislowski commented on backend/server.js
> +  }
nice model

2021-06-05 08:57 UTC, KarolCislowski commented on backend/server.js
> +})
great 👍🏻

2021-06-05 08:57 UTC, KarolCislowski commented on frontend/src/components/Form.js
> +          })
Nice 👍🏻

2021-06-05 08:57 UTC, KarolCislowski commented on frontend/src/components/Main.js
> +  }, [accessToken, dispatch])
the second useEffect is for the situation when you have accessToken, so why do not input logic from it as the `else` block into the first one? 

```jsx
useEffect(() => {
    if (!accessToken) {
      history.push('/login')
    } else {
      const config = { ... }
      ...
    }
  }, [accessToken, history])
```

2021-06-05 08:57 UTC, KarolCislowski commented on frontend/src/reducers/secrets.js
> +export default secrets
really nice 👍🏻

2021-06-05 08:57 UTC, KarolCislowski commented on frontend/src/reducers/user.js
> +export default user
You need to store your data in the local storage to avoid logging out your user after refreshing the page.

2021-06-06 10:27 UTC, KarolCislowski approved these changes
Now it is beautiful 😻

2022-04-21 14:54 UTC, closed without merging