Project 20 Auth Julia Ros & Ann-Sofi Jönsson
Technigo/project-auth pull request #109
Opened 2021-05-28 12:32 UTC by Ann-Sofi

Link to my deployed project:

https://project-authorization-2021.netlify.app/

2021-06-02 15:19 UTC, rrpersson reviewed
Well done on the project. I like your styling and color scheme! 
Good use of styled components as well!
Your code is easy to follow and it looks easy to maintain as well!

2021-06-02 15:19 UTC, rrpersson commented on backend/server.js
> +dotenv.config()
Good use of dot env

2021-06-02 15:19 UTC, rrpersson commented on backend/server.js
> +  res.json({secret: 'This is a secret message'})
Is it rellay secret if I can read it! ;)

2021-06-02 15:19 UTC, rrpersson commented on frontend/src/components/SecretPage.js
> +`
Nice use of styled components!

2021-06-02 15:19 UTC, rrpersson commented on frontend/src/components/SignIn.js
> +          placeholder='•••••'
Nice placeholder! :)

2021-06-02 15:19 UTC, rrpersson commented on frontend/src/reusables/urls.js
> +export const API_URL = (slug) => `${BASE_URL}/${slug}`
Good use of an urls file

2021-06-02 15:32 UTC, CarolineF3 commented on README.md
> +https://julia-annsofi-secret-api.herokuapp.com/
Really nice ReadMe, very neat and descriptive. :)

2021-06-05 09:06 UTC, KarolCislowski requested changes
It is really nice app but you need to clean it up and persist your user in the local storage to avoid refreshing.

Because your graduation is so soon please let me know on slack (a short note with a link to this PR) when you finish fixing your app.

2021-06-05 09:06 UTC, KarolCislowski commented on README.md
> +https://project-authorization-2021.netlify.app/
To fix it you need to create `_redirects` file in the `public` directory of your react project and paste it inside:
``` 
/* /index.html 200
```

![image](https://user-images.githubusercontent.com/50926159/120886292-7b362880-c5ed-11eb-8b7d-3bf8650cb801.png)

2021-06-05 09:06 UTC, KarolCislowski commented on backend/server.js
> +})
nice model 👍🏻

2021-06-05 09:06 UTC, KarolCislowski commented on backend/server.js
> +})
nice middlewares 👍🏻

2021-06-05 09:06 UTC, KarolCislowski commented on frontend/src/components/SecretPage.js
> +    })
Nice 👍🏻

2021-06-05 09:06 UTC, KarolCislowski commented on frontend/src/components/SignIn.js
> +        console.log(data)
🧹 console.log 🧹

2021-06-05 09:06 UTC, KarolCislowski commented on frontend/src/reducers/user.js
> +export default user
You need to store your data in the local storage to avoid logging out your user after refreshing the page.

2021-06-08 05:42 UTC, KarolCislowski approved these changes
Nice project, you just need to fix the netlify issue by adding `_redirects` file to the public folder.

2022-04-21 14:54 UTC, closed without merging