week 20 - Rasmus & Caroline
Technigo/project-auth pull request #123
Opened 2021-05-30 11:48 UTC by rrpersson

Live website: https://week20-projectauth.netlify.app/

Github: https://github.com/Technigo/project-auth

2021-06-02 17:44 UTC, Aepera approved these changes
Beautiful styling! 🦄 Nice frontend with the happy thoughts behind the authentication.
Nice functions and clean code, nicely described by comments. 😊

2021-06-02 17:44 UTC, Aepera commented on backend/server.js
> +  process.env.MONGO_URL ||
We are curious why you choose to place the connection string here, on the right side of the OR sign?

2021-06-02 17:44 UTC, Aepera commented on backend/server.js
> +    res.status(400).json({ message: "Invalid request", error });
Nice error handling! 👍 Could be used to send alert messages to frontend.

2021-06-02 17:44 UTC, Aepera commented on backend/server.js
> +// IF the username and the encpyted password match what's in the databse then the user is logged in and an accessToken is passed back to the user via tha API.
Nice and descriptive comments!

2021-06-02 17:44 UTC, Aepera commented on frontend/src/App.js
> +    <>
The fragments are not needed since BrowserRouter is the outermost element.

2021-06-02 17:44 UTC, Aepera commented on frontend/src/components/Header.js
> +import React from "react";
Is this component used somewhere? If not it could be deleted? 😀

2021-06-02 17:44 UTC, Aepera commented on frontend/src/pages/Index.js
> +  const API_THOUGHTS = "https://week20-project-auth.herokuapp.com/thoughts";
URL:s can also be stored in separate files!

2021-06-02 17:44 UTC, Aepera commented on frontend/src/pages/Index.js
> +      .then((data) => console.log(data));
Remove console.log 😎

2021-06-02 17:44 UTC, Aepera commented on frontend/src/pages/Index.js
> +  const onButtonClick = (e) => {
This post function doesn´t seem to work properly, new messages do not appear in the list immediately but only after posting another message or reloading the page.

2021-06-05 22:40 UTC, KarolCislowski requested changes
It is really nice app but you need to persist your user in the local storage to avoid refreshing.


Because your graduation is so soon please let me know on slack (a short note with a link to this PR) when you finish fixing your app.

2021-06-05 22:40 UTC, KarolCislowski commented on frontend/public/index.html
>  </html>
To fix it you need to create `_redirects` file in the `public` directory of your react project and paste it inside:
``` 
/* /index.html 200
```

![image](https://user-images.githubusercontent.com/50926159/120907081-0ac7ef80-c65f-11eb-8f44-768801c22560.png)

2021-06-05 22:40 UTC, KarolCislowski commented on backend/server.js
> +  },
Nice model 👍🏻

2021-06-05 22:40 UTC, KarolCislowski commented on backend/server.js
> +});
nicely reused code 👍🏻

2021-06-05 22:40 UTC, KarolCislowski commented on frontend/src/pages/IndexStyle.css
> +.thought-wrapper {
Your site is beautifully styled 😻

2021-06-05 22:40 UTC, KarolCislowski commented on frontend/src/reducers/user.js
> +export default user;
You need to store your data in the local storage to avoid logging out your user after refreshing the page.

2021-06-08 06:37 UTC, KarolCislowski approved these changes
Great work 🥇

2022-04-21 14:55 UTC, closed without merging