Project auth week 20
Technigo/project-auth pull request #124
Opened 2021-05-30 15:27 UTC by FD000

Link to my deployed project:
https://epic-bassi-8dc187.netlify.app/login

Group members:
- Fethullah Dincer
- Martin Danielsson
- Emma Bartl

2021-06-03 10:03 UTC, klimenko3007 approved these changes
Great job, guys! I am not sure whether the styling was part of the assignment for this week, so I approve the request and leave to Karol to decide your final fate :D!

2021-06-03 10:03 UTC, klimenko3007 commented on frontend/src/reducers/credentials.js
> +        }
That is a really long ternary operator that is very difficult to read. Perhaps, consider if statements?

2021-06-05 22:48 UTC, KarolCislowski requested changes
It is really nice app but you need to clean it up, style it a little more, and persist your user in the local storage to avoid refreshing.


Because your graduation is so soon please let me know on slack (a short note with a link to this PR) when you finish fixing your app.

2021-06-05 22:48 UTC, KarolCislowski commented on README.md
> +https://epic-bassi-8dc187.netlify.app/
To fix it you need to create `_redirects` file in the `public` directory of your react project and paste it inside:
``` 
/* /index.html 200
```

![image](https://user-images.githubusercontent.com/50926159/120907224-1ff14e00-c660-11eb-8f24-d188aa585391.png)

2021-06-05 22:48 UTC, KarolCislowski commented on backend/server copy.js
> +  }
nice model 👍🏻

2021-06-05 22:48 UTC, KarolCislowski commented on backend/server copy.js
> +// });
🧹

2021-06-05 22:48 UTC, KarolCislowski commented on backend/server copy.js
> +import express from 'express'
why is this file exist?

2021-06-05 22:48 UTC, KarolCislowski commented on frontend/src/reducers/credentials.js
> +        secret: ''
You need to store your data in the local storage to avoid logging out your user after refreshing the page.

2021-06-19 11:13 UTC, KarolCislowski approved these changes
Great APP 🥳

2022-04-21 14:54 UTC, closed without merging