Week 20/Darcy & Astrid
Technigo/project-auth pull request #125
Opened 2021-05-30 16:14 UTC by darcywinterhill

Link to my deployed project:
https://super-secret-auth.netlify.app/

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2021-06-02 17:46 UTC, Pauan8 approved these changes
Nice well functioning page, good work! 🥇

2021-06-02 17:46 UTC, Pauan8 commented on backend/server.js
> +    maxlength: [18, 'Max 18 characters']
Good with the extra info in the brackets for error handling :)

2021-06-02 17:46 UTC, Pauan8 commented on backend/server.js
> +    })
It would be good with success: false here maybe when failing?

2021-06-02 17:46 UTC, Pauan8 commented on frontend/src/components/Login.js
> +          Swal.fire(data.message)
Nice error messages with sweetalert 💯

2021-06-02 17:46 UTC, Pauan8 commented on frontend/src/components/Signup.js
> +}
Signup is very similar to login, could maybe be some component with props instead of two different pages?

2021-06-02 17:46 UTC, Pauan8 commented on frontend/src/pages/SecretPage.js
> +      </lottie-player>
Cute lottie 👍

2021-06-05 22:56 UTC, KarolCislowski requested changes
It is really nice app but you need to persist your user in the local storage to avoid refreshing.

Because your graduation is so soon please let me know on slack (a short note with a link to this PR) when you finish fixing your app.

2021-06-05 22:56 UTC, KarolCislowski commented on README.md
> +https://super-secret-auth.netlify.app/
To fix it you need to create `_redirects` file in the `public` directory of your react project and paste it inside:
``` 
/* /index.html 200
```
![image](https://user-images.githubusercontent.com/50926159/120907409-60050080-c661-11eb-9e54-65d0c4be552a.png)

2021-06-05 22:56 UTC, KarolCislowski commented on backend/server.js
> +  }
Nice model 👍🏻

2021-06-05 22:56 UTC, KarolCislowski commented on frontend/src/components/Login.js
> +            dispatch(user.actions.setErrors(null))
👍🏻

2021-06-05 22:56 UTC, KarolCislowski commented on frontend/src/components/Signup.js
> +const Signup = () => {
both your forms look 99% the same, maybe it is a good idea to create one and pass differences via props?

2021-06-05 22:56 UTC, KarolCislowski commented on frontend/src/reducers/user.js
> +    },
You need to store your data in the local storage to avoid logging out your user after refreshing the page.

2021-06-06 10:24 UTC, KarolCislowski approved these changes
Great Work!

2022-04-21 14:54 UTC, closed without merging