Project Authentication - Iriana & Daniela
Technigo/project-auth pull request #129
Opened 2021-05-30 21:51 UTC by dannuzak

Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2021-06-02 19:08 UTC, MarySparrow requested changes
This is our last code review 😢
We are really happy to see that you are using styled components ! ✨🔥 Clean and well-written code as always. We are just missing the final result, the link to the deployed project so that we can watch your code do its magic and press that Approve button! 🍭
🦄 🌈Maybe just have quick overview to remove some extra spaces here and there. ✨/Therese, Anna-Kaisa and Maria

2021-06-06 09:32 UTC, KarolCislowski requested changes
It is really nice app but you need to clean it up and persist your user in the local storage to avoid refreshing.

Because your graduation is so soon please let me know on slack (a short note with a link to this PR) when you finish fixing your app.

2021-06-06 09:32 UTC, KarolCislowski commented on README.md
> +FE: https://vigorous-gates-2c453b.netlify.app/signin
To fix it you need to create `_redirects` file in the `public` directory of your react project and paste it inside:
``` 
/* /index.html 200
```


![image](https://user-images.githubusercontent.com/50926159/120919420-ca498f80-c6b9-11eb-8774-4cb452a25e21.png)

2021-06-06 09:32 UTC, KarolCislowski commented on backend/server.js
> +  }
nice model!

2021-06-06 09:32 UTC, KarolCislowski commented on frontend/src/App.js
> +          <Route path="/signup" component={Signup} />
both forms look 99% the same, maybe it would be nice to build 1 and pass differences as props?

2021-06-06 09:32 UTC, KarolCislowski commented on frontend/src/components/Main.js
> +  }, [accessToken, dispatch]); // I added the second arg because of an error suggesting that
why 2 effects when you can have 1?

```jsx

useEffect(() => {
    if (!accessToken) {
      history.push('/login')
    } else {
      const options = { ...}
      ...
    }
  }, [accessToken, history, dispatch])

```

2021-06-06 09:32 UTC, KarolCislowski commented on frontend/src/components/Main.js
> +  console.log(thoughtsItems)
🧹 console.log 🧹

2021-06-06 09:32 UTC, KarolCislowski commented on frontend/src/reducers/user.js
> +export default user
You need to store your data in the local storage to avoid logging out your user after refreshing the page.

2021-07-04 17:26 UTC, KarolCislowski approved these changes
Great job 🎉

2022-04-21 14:54 UTC, closed without merging