Moa and Karan - Week 20 - Project Authentication
Technigo/project-auth pull request #57
Opened 2021-01-15 09:23 UTC by karanmann

# Link to my deployed project:

- FrontEnd : wk20-api-auth.netlify.app
- BackEnd : https://login-logout-authentication.herokuapp.com/

# My reflections on how this week's project turned out:

This project was fun and really challenging. The scope of the project was much bigger than the previous weeks which was a bit of a surprise. It was also great to work as a team as this was our last project in the course.

# We aimed for the blue level this time around.

2021-01-15 14:40 UTC, sandra-shumanteva-kaevska approved these changes
Great Job Moa and Karan you achieved all blue level requirements. The code was clean and easy to read. Keep up with the good work :D

2021-01-15 14:40 UTC, sandra-shumanteva-kaevska commented on README.md
> +- FrontEnd : wk20-api-auth.netlify.app
Maybe it is better to write full link which is clickable :)

2021-01-15 14:40 UTC, sandra-shumanteva-kaevska commented on backend/server.js
> +  email: {
Well done with adding the email in sign-in  form 💯

2021-01-15 14:40 UTC, sandra-shumanteva-kaevska commented on backend/server.js
> +  const secretMessage = `This is a super secret message for ${req.user.name}`
When you login and reveal the secret message it is showing like this: {"secretMessage":"This is a super secret message for test"}
To fix this you need to wrap your template string in {} like this: const secretMessage = {`This is a super secret message for ${req.user.name}`}

2021-01-21 14:05 UTC, KarolCislowski requested changes
This app has a very big potential, but you need to do 2 things:

- store your user in the local storage to stop logging out on page refresh,
- add `_redirects` file to the `public` directory inside of your frontend and save the following code  in it: `/* /index.html 200`   It will stop netlify from showing a default error page.

And the last thing: Please, make yourself a favour and style your app nicely. It should take only a few minutes but it can open some extra doors 😄

2021-01-22 09:24 UTC, karanmann commented
Hej Karol,

Thank you for the feedback. We have made the requested changes as you mentioned in your bullet points.
We have decided to keep the styling as it is for now and go back to it later. And the same goes for the signup to login.
We do understand it would be a good UX but when we created it we thought this was the best practice.  

/ Moa and Karan

2021-01-24 15:39 UTC, KarolCislowski approved these changes
Now it works nice 😺  Great job 🦄

2021-03-09 13:41 UTC, closed without merging