Project auth - by Olof & Bäm
Technigo/project-auth pull request #59
Opened 2021-01-15 11:42 UTC by luuf81

**Link to my deployed project:**

Frontend: https://project-auth-bamolof.netlify.app/
Backend: https://project-auth-olof.herokuapp.com/

**My reflections on how this week's project turned out:**

It was fun to finally create a app that brings everything together - backend, frontend, authentication. Will be great lessons for final project! 

Things I'd like to have clarified or explained in more detail:

Some things could probably be further reinforced by looking at the recorded videos/lectures a few more times :)

// Olof & Bäm

2021-01-20 12:26 UTC, Bluepoisson approved these changes
Great job Bäm and Olof! You've created a stylish frontend with a complex backend enabling user to post and save notes. You successfully connected them 🥇  We also appreciated the wink to the happy thoughts project, reusing the input component 😄 Approved!

2021-01-20 12:26 UTC, Bluepoisson commented on frontend/src/components/LoginForm.js
> +  const dispatch = useDispatch()
Semicolons to be or not to be? Try to be consistent in the usage of them.

2021-01-20 12:26 UTC, Bluepoisson commented on frontend/src/components/LoginForm.js
> +    dispatch(user.actions.setStatusMessage({ statusMessage: "Login Success" }));
This message is shown when we have logged out. Perhaps change it's scope?

2021-01-20 12:26 UTC, Bluepoisson commented on frontend/src/components/Profile.js
> +    return <div>Please log in</div>
Where is this div shown?

2021-01-20 12:26 UTC, Bluepoisson commented on frontend/src/styling/form.js
> +
Remove blank spaces :)

2021-01-20 12:26 UTC, Bluepoisson commented on frontend/src/components/Notes.js
> +import { Button, ProfileSection } from '../styling/form'
Great with styling components, keeps the code clean.

2021-01-21 16:14 UTC, KarolCislowski requested changes
This is an awesome project! It is very ambitious 🌈 

Smart that you reused idea from the happy thoughts! And this picture on the logging page is so nice! 

To get your black belts you need to fix the refresh page=loggout issue! Good luck!

2021-01-21 16:14 UTC, KarolCislowski commented on backend/server.js
> +  ref: 'User'
indentation 😄

2021-01-21 16:14 UTC, KarolCislowski commented on backend/server.js
> +    res.status(404).json({ error: 'User not found' });
this endpoint is adding data so status should be `400` and message should be something like `couldn't create new note`.

2021-01-21 16:14 UTC, KarolCislowski commented on frontend/src/reducers/user.js
> +})
You need to store your user data in the local storage, to prevent logging out after refreshing the page 😺

2021-01-26 14:24 UTC, KarolCislowski approved these changes
And now it is a pure magic 🦄 🌈

2021-03-09 13:41 UTC, closed without merging