Project Auth - Anna Hellqvist, Evelina Berg, Mats Johansen
Technigo/project-auth pull request #66
Opened 2021-01-15 15:44 UTC by AnnaHellqvist

Link to my deployed project:
https://auth-project-api.herokuapp.com/

My reflections on how this week's project turned out:
It has been a difficult week, connecting frontend and backend. It was good to get this experience before the final project. 
It would have been good to have some information about security and authentication earlier in the sprint. It is a lot of information to understand in a week and it would have been nice to be more prepared before this project.

2021-01-20 16:44 UTC, Gabbi-89 approved these changes
Nice project ⭐ You have fulfilled all requirements with good messages and good commented code! We really love your styling 🤩 and you did a great work having the styling in its own files. 

Good work to have separated the functions in different components which makes the code cleaner. We do also like that you used the Navigation Router! 


// Sara Stjernberg @stjernberg & Gabriella Bolin

2021-01-20 16:44 UTC, Gabbi-89 commented on backend/server.js
> +
Nice backend code! Easy to follow and good comments! You have used error messages and you have all needed endpoints. ⭐

2021-01-20 16:44 UTC, Gabbi-89 commented on frontend/src/App.js
> +        <Switch>
Cool that you used the Navigation Routes and that you use reducers. 😊

2021-01-20 16:44 UTC, Gabbi-89 commented on frontend/src/lib/Container.js
> +export const Container = styled.div`
Nice that you have made a separate library for the styling and that you have them in different files. 💯 
Please check your indentations, you miss them for some of the styling components.

2021-01-20 16:44 UTC, Gabbi-89 commented on frontend/src/lib/InputField.js
> +  )
Nice that you use props here and that you try to use it :)  Maybe it doesn't save you that much code but nice that you got it to work!

2021-01-20 16:44 UTC, Gabbi-89 commented on frontend/src/lib/Button.js
> +export const Button = ({title, onClickFunc}) => {
Cool 🤩

2021-01-20 16:44 UTC, Gabbi-89 commented on backend/server.js
> +
@stjernberg

2021-01-22 17:44 UTC, KarolCislowski requested changes
This is a nice project 🦄 but to meet the blue level you need to make your user logged in even after refreshing the page. Tips on how to do it are at the beginning of the documentation. 

Good luck 🌈

2021-01-22 17:44 UTC, KarolCislowski commented on backend/server.js
> +      userName: user.name,
You are sending all the data needed by your frontend to log in your users on spot, but you decided to force them to fill another form? It is not a nice user experience 😭

2021-01-22 17:44 UTC, KarolCislowski commented on frontend/src/App.js
> +          <Route path="/:id/user">
I think the better solution is to make your user component get access to the id by param or from the reducer.  🤓

2021-01-22 17:44 UTC, KarolCislowski commented on frontend/src/components/LoginForm.js
> +};
You have two identical forms. you could create one with two modes (in/up) passed via prop.

2021-01-22 17:44 UTC, KarolCislowski commented on frontend/src/components/UserPage.js
> +    // };
You should clean your code from commented out pieces of code 🤓

2021-01-22 17:44 UTC, KarolCislowski commented on frontend/src/reducer/user.js
> +});
Nice that you used the redux to store your user, but you need to think about storing some of the data in the local storage, to stop logging out while refreshing the page. 🤓

2021-01-27 12:28 UTC, KarolCislowski approved these changes
After the discussion with teachers about this assignment, we decided to approve this project without implementing the local storage functionality. 

However for the future, please remember to store your users' authentication data in your browser to make your UX good.

Good luck with your Final Project! 🍀

2021-03-09 13:41 UTC, closed without merging