Week 20 - Karin Nordkvist & Petra Almgren (Auth 🗝)
Technigo/project-auth pull request #70
Opened 2021-01-16 20:55 UTC by karinnordkvist

**Link to our deployed project:**
* Frontend: https://project-auth-by-karin-and-petra.netlify.app/
* Backend: https://auth-by-karin-petra.herokuapp.com/

**My reflections on how this week's project turned out:** 
The project went well and we worked great together! 😄 

**Things I'd like to have clarified or explained in more detail:**
The subject is really big and it would have been super interesting to get to work with authentication even more. 🌟

2021-01-23 09:49 UTC, KarolCislowski requested changes
Great project! Your code is nice and clean! 🥇 

But I need to ask you to fix the logging out on refresh issue 🙏🏻 

Good luck 😸

2021-01-23 09:49 UTC, KarolCislowski commented on backend/server.js
> +      .status(401)
Good error status 👍🏻

2021-01-23 09:49 UTC, KarolCislowski commented on frontend/src/components/Content.js
> +const Wrapper = styled.div`
Nice that you used styled-components 💟

2021-01-23 09:49 UTC, KarolCislowski commented on frontend/src/reducers/users.js
> +};
Reducer is a great choice to store your user data 🥇 but you need to save some of them in the local storage to stop losing your data after refreshing the page.

2021-01-23 20:37 UTC, emma-tech reviewed
Good job Karin and Petra! Really nice and well structured code, and I looove the frontend, so nice and clean styling! 😍

2021-01-23 20:37 UTC, emma-tech commented on backend/server.js
> +  name: {
Really nice and well structured schema! :)

2021-01-23 20:37 UTC, emma-tech commented on backend/server.js
> +    res
Nice and well structured code 👍

2021-01-23 20:37 UTC, emma-tech commented on backend/server.js
> +app.get('/private', authenticateUser);
Really cool that you implemented this private endpoint as well 👍

2021-01-23 20:37 UTC, emma-tech commented on backend/server.js
> +  const user = await User.findOne({ email: req.body.email });
Good that you remembered about findOne() here! 🙌

2021-01-23 20:37 UTC, emma-tech commented on backend/server.js
> +      .status(200)
I was wondering if a 201 status code is more appropriate here, as we are _creating_ and posting a new user? :)

2021-01-23 20:37 UTC, emma-tech commented on backend/server.js
> +    required: [true, 'You have to enter an email address.'],
Good job with validation 👏

2021-01-25 07:16 UTC, aagneshansson commented on frontend/src/components/Main.js
> +
Love that you added a specific component for handling whether the user is logged in/not 🙌

2021-01-27 12:13 UTC, KarolCislowski approved these changes
After the discussion with teachers about this assignment, we decided to approve this project without implementing the local storage functionality. 

However for the future, please remember to store your users' authentication data in your browser to make your UX good.

Good luck with your Final Project! 🍀

2021-03-09 13:41 UTC, closed without merging