Emma & Agnes login app
Technigo/project-auth pull request #72
Opened 2021-01-17 10:13 UTC by aagneshansson

Link to my deployed project:
https://agnes-emma-login.herokuapp.com/
https://agnes-emma-login.netlify.app/

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:
We'd like some feedback regarding our error messages and how to tweak them.

2021-01-20 21:20 UTC, AnnaHellqvist requested changes
You have fulfilled almost every blue level requirement. We cannot see an error message when creating a user that does not fulfill the requirements. There is an 400 showing in the console but there should be something visible in the frontend, you could use something similar as you have for the login form :)  I like your styling and the cute robot greeting ✨

2021-01-20 21:20 UTC, AnnaHellqvist commented on frontend/src/components/SignUpForm.js
> +
Seems like maybe you haven't had the time to finish yet? I cannot see an error message in the frontend if I tried to register and it didn't work

2021-01-20 21:20 UTC, AnnaHellqvist commented on frontend/src/components/SignUpForm.js
> +
And you could reset your local states to empty the input fields after pressing the button :)

2021-01-23 10:52 UTC, KarolCislowski requested changes
This is a very nice app 🦄 but you need to fix a few issues:

1. Provide error messages. 🛑 
2. Finnish sign-up form so your users will be logged in after you save their data to the database 🚶🏻 
3. Store your user in the local storage to make them stay in you after refreshing the page 🧑🏻‍🤝‍🧑🏻 

Good Luck 🌈

2021-01-23 10:52 UTC, KarolCislowski commented on frontend/src/components/SignUpForm.js
> +    };
This needs to be finished because you leaving your users unlogged, and without any clue, if your app is working or not 😢

2021-01-23 10:52 UTC, KarolCislowski commented on frontend/src/reducers/user.js
> +})
Reducer is a great place to manage your users, but you need to store some of a data in the local storage to make your users still logged in after page refresh. 🤓

2021-02-10 13:25 UTC, HIPPIEKICK commented
> This is a very nice app 🦄 but you need to fix a few issues:
> 
> 1. Provide error messages. 🛑
> 2. Finnish sign-up form so your users will be logged in after you save their data to the database 🚶🏻
> 3. Store your user in the local storage to make them stay in you after refreshing the page 🧑🏻‍🤝‍🧑🏻
> 
> Good Luck 🌈

2021-02-10 13:29 UTC, HIPPIEKICK commented
Hi Emma & Agnes! Focus on the success/error messages as per this blue requirement:

> - Your API should validate the user input when creating a new user, and return error messages which could be shown by the frontend (displaying the errors in a nice way in the frontend is a stretch goal - its fine to just show 'Something went wrong' on the frontend if you run out of time)

and remove commented out code and console.logs as local storage was only mentioned in the brief and not the requirements.

2021-03-09 13:47 UTC, closed without merging