Project Auth by Max and Sandrine
Technigo/project-auth pull request #74
Opened 2021-01-17 11:58 UTC by MindstormingAB

Link to our deployed project: https://max-sandrine-auth-app.netlify.app/
Link to our API: https://max-sandrine-auth-api.herokuapp.com/

Our reflections on how this week's project turned out: This week's project was pretty difficult because it required the new backend knowledge related to authentication we learned during the week as well as all the React/Redux skills we previously acquired during the Bootcamp. It was very challenging to build both frontend and backend from scratch.

Things I'd like to have clarified or explained in more detail: -

2021-01-18 16:08 UTC, pwangy approved these changes
Really nice work, you two. 💪 

This week's assignment was really difficult-- and you gave us a few reminders of things we had forgotten, so thank you for that! How nice that you went the extra step to show a personalized welcome screen upon login. All those little touches you added were appreciated. 

Most of the actionable comments are minor clean-up or consistency notes; or general food-for-thought. 😁

2021-01-18 16:08 UTC, pwangy commented on frontend/src/index.css
> +  /* border-radius: 25px; */
Remove commented out line.

2021-01-18 16:08 UTC, pwangy commented on frontend/src/index.css
> +  margin: 0 0 16px 0;
perhaps just margin-bottom?

2021-01-23 11:39 UTC, KarolCislowski requested changes
It is a great app! Good job 🦄 

You need to fix only one issue with storing your data in the local storage.

Good luck 🌈

2021-01-23 11:39 UTC, KarolCislowski commented on backend/server.js
> +userSchema.pre("save", async function (next) {
nice use of  `pre()`

2021-01-23 11:39 UTC, KarolCislowski commented on backend/server.js
> +const listEndpoints = require("express-list-endpoints");
You should import it on top of your script with `import/from` syntax.

2021-01-23 11:39 UTC, KarolCislowski commented on backend/server.js
> +      var msg = `This site ${origin} does not have an access. Only specific domains are allowed to access it`
Nice that you implement this logic, but remember that you shouldn't use `var` any more. `const` would be proper here. 🤓

2021-01-23 11:39 UTC, KarolCislowski commented on backend/server.js
> +app.post("/users/:userId/profile", async (req, res) => {
It is not a good practice to pass any user data within a URL. You should use the request body to pass it to the server. 🤓

2021-01-23 11:39 UTC, KarolCislowski commented on frontend/src/reducers/user.js
> +});
Reducer is a great place to manage your users but you need to store some data in the local storage to make them stay legged in after they refresh the page 🤓

2021-01-23 17:15 UTC, MindstormingAB commented
Hi @KarolCislowski and @pwangy 
Thank you for reviewing this repository.
I did the following changes with regard to your feedback:
- added a local storage in frontend
- moved userId from the endpoint url to a header
- replaced POST with PATCH
- fixed smaller "bits and bobs"

2021-01-24 13:58 UTC, KarolCislowski approved these changes
Great work!

2021-03-09 13:41 UTC, closed without merging