Pull req for project authorization / Kat and Liza
Technigo/project-auth pull request #76
Opened 2021-01-17 13:57 UTC by Katsiez

Link to my deployed project:
Backend = https://project-auth-liza-kat.herokuapp.com/
Frontend = https://practical-mestorf-d4dfd7.netlify.app/sessions

My reflections on how this week's project turned out:
Turned out good after a lot of hours of working on it together. Much more complicated than we anticipated! :D

Things I'd like to have clarified or explained in more detail:
How I still have a functioning brain after all this mumbo jumbo lol.

2021-01-20 21:54 UTC, jonnaru approved these changes
Hey! Great work 🤩 Really inspiring. Loved reading your code. Super cute login-page. I think there is a problem, perhaps between router and netlify. Sometimes I get this error-messages from netlify 🤷‍♀️ But I got all the way to the secret message and loged out 🙌

2021-01-20 21:54 UTC, jonnaru commented on backend/server.js
> +import endpoints from "express-list-endpoints";
Cool, didn't know about this 😎

2021-01-20 21:54 UTC, jonnaru commented on backend/server.js
> +      password: user.password
Are you sure sending back password is a good idea, even if it's hashed? 🧐

2021-01-20 21:54 UTC, jonnaru commented on frontend/src/App.js
> +};
Redux and router!!! 🤩

2021-01-20 21:54 UTC, jonnaru commented on frontend/src/components/Home.js
> +        </AnimatedBg>
Pretty ⭐️

2021-01-20 21:54 UTC, jonnaru commented on frontend/src/components/Login.js
> +      });
Good idea!

2021-01-20 21:54 UTC, jonnaru commented on frontend/src/components/UserProfile.js
> +`;
If you are using the same styling in more components than one, like this one, maybe you can move the styling out from the component and then import this image styling 😍

2021-01-23 13:29 UTC, KarolCislowski requested changes
It is a very nice project 🦄 

Please fix the losing user on refresh issue and it will be a magical app 🌈

2021-01-23 13:29 UTC, KarolCislowski commented on frontend/src/components/Home.js
> +const Image = styled.main`
nice that you used styled-components ❤️

2021-01-23 13:29 UTC, KarolCislowski commented on frontend/src/reducers/user.js
> +});
Reducer is a great place to manage your users, but you need to store some data in the local storage to keep your users logged in after they refresh the page. 🤓

2021-01-27 12:09 UTC, KarolCislowski approved these changes
After the discussion with teachers about this assignment, we decided to approve this project without implementing the local storage functionality. 

However for the future, please remember to store your users' authentication data in your browser to make your UX good.

Good luck with your Final Project! 🍀

2021-03-09 13:42 UTC, closed without merging