Project-Auth-Cornelia and Joel
Technigo/project-auth pull request #77
Opened 2021-01-17 17:17 UTC by JHarde

- Frontend: https://modest-hamilton-9de3b4.netlify.app/

- Backend: https://project-auth-joel-cornelia.herokuapp.com/

2021-01-18 16:20 UTC, Thessan approved these changes
Great job Cornelia and Joel 🎉  You have completed blue requirements for this project. We were impressed of your usage of styled components and that you've used findOneAndUpdate method 👍  See comments for some UI suggestions.

/ Therése & Rebeka

2021-01-18 16:20 UTC, Thessan commented on frontend/src/Styling/StyledComponents.js
> +  color: white;
Maybe write this line of code with HEX as well?

2021-01-18 16:20 UTC, Thessan commented on frontend/src/Styling/StyledComponents.js
> +  margin: 0px;
0; is enough 😊

2021-01-18 16:20 UTC, Thessan commented on frontend/src/Styling/StyledComponents.js
> +    color: #5b8f8c;
nice use of pseudo-element

2021-01-18 16:20 UTC, Thessan commented on frontend/src/Styling/StyledComponents.js
> +  color: ${(props) => (props.success ? "#41b3a3" : "#E24030")};
great that you've used props to style the different messages 👍

2021-01-18 16:20 UTC, Thessan commented on frontend/src/user.js
> +      console.log(`status message: ${statusMessage}`);
you can delete these console.log

2021-01-23 13:42 UTC, KarolCislowski requested changes
This is a very nice project 👍🏻 Great job!

Please fix the issue of unwanted logging out on page refresh and it will be an awesome app.

2021-01-23 13:42 UTC, KarolCislowski commented on backend/server.js
> +const listEndpoints = require("express-list-endpoints");
You should add this library using the `import/from` syntax 🤓

2021-01-23 13:42 UTC, KarolCislowski commented on frontend/src/Styling/StyledComponents.js
> +import styled from "styled-components";
Great idea to create the UI library for your project 🌈

2021-01-23 13:42 UTC, KarolCislowski commented on frontend/src/user.js
> +});
Reducer is a great place to manage your users but you need to store some of your data in the local storage to keep your users logged in after they refresh the page 🤓

2021-01-27 12:06 UTC, KarolCislowski approved these changes
After the discussion with teachers about this assignment, we decided to approve this project without implementing the local storage functionality. 

However for the future, please remember to store your users' authentication data in your browser to make your UX good.

Good luck with your Final Project! 🍀

2021-03-09 13:42 UTC, closed without merging