Project Auth - Moa, Johanna & Linda
Technigo/project-auth pull request #81
Opened 2021-01-17 21:56 UTC by lindahz

**Link to my deployed project:** 
https://auth-by-jml.netlify.app/
https://git.heroku.com/project-auth-technigo.git

**My reflections on how this week's project turned out:**
Good team work.

**Things I'd like to have clarified or explained in more detail:**
We did not manage to implement validation in backend for password and email (max/min length). We tried the code along with Van from Wednesday's lecture and created a schema, but we did not succeed. Is it because we decided to go with one form and two onClick functions, instead of two forms and two onSubmit functions?

2021-01-20 14:40 UTC, carolinebirgersson reviewed
Good job with the project! Nice that you solved the validation in frontend. Clean and easy to read your code all the way through frontend and backend.  We like that you kept the app as clean as possible! Be proud 🌟

2021-01-20 14:40 UTC, carolinebirgersson commented on backend/server.js
> +
Nice and clean model! Consider to update the model with maxLength: 12, since it's written in the frontend.

2021-01-20 14:40 UTC, carolinebirgersson commented on backend/server.js
> +    res.status(201).json({ id: saved._id, accessToken: saved.accessToken, message: 'Your profile has been created successfully!' })
Smart with the message field in the json response! 👏🏼

2021-01-20 14:40 UTC, carolinebirgersson commented on frontend/public/index.html
>      <title>Technigo React App</title>
Consider to create a new title for your project!

2021-01-20 14:40 UTC, carolinebirgersson commented on frontend/src/App.js
>    )
Clean to just have one component!

2021-01-20 14:40 UTC, carolinebirgersson commented on frontend/src/components/Login.js
> +
Great that you've created url-variables! Makes the code further down easy to read.

2021-01-20 14:40 UTC, carolinebirgersson commented on frontend/src/components/Login.js
> +  }
Impressive that you created a validation for the email. Good job! 👌

2021-01-20 14:40 UTC, carolinebirgersson commented on frontend/src/components/Login.js
> +              />
Consider to add maxLength="12" since the button is disabled if you write more than 12. It goes for the password as well.

2021-01-23 15:35 UTC, KarolCislowski requested changes
Please store your logged-in user, use this saved data to retrieve secret, and create logout functionality which will remove your user from the storage.

2021-01-23 15:35 UTC, KarolCislowski commented on frontend/src/components/Login.js
> +        handleSecrets(json.accessToken)
The clue of this app was not to show something secret but create the logging system. Here you didn't save token anywhere. You created a situation where your users need to fill the form every time they want something from your server. 

At the beginning of the documentation is the information that you need to store your token in the local storage, and then you can use it without sending your form over and over again.

2021-01-27 11:58 UTC, KarolCislowski approved these changes
After the discussion with teachers about this assignment, we decided to approve this project without implementing the local storage functionality. 

However for the future, please remember to store your users' authentication data in your browser to make your UX good.

Good luck with your Final Project! 🦄

2021-03-09 13:42 UTC, closed without merging